//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class HelloDll {
  public static Classifier GetInstance() {
    global::System.IntPtr cPtr = HelloDllPINVOKE.GetInstance();
    Classifier ret = (cPtr == global::System.IntPtr.Zero) ? null : new Classifier(cPtr, false);
    return ret;
  }

}
